# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  Assignment_config = debug_x64
endif
ifeq ($(config),release_x64)
  Assignment_config = release_x64
endif

PROJECTS := Assignment

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Assignment:
ifneq (,$(Assignment_config))
	@echo "==== Building Assignment ($(Assignment_config)) ===="
	@${MAKE} --no-print-directory -C build -f Makefile config=$(Assignment_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  release_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Assignment"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"